---
- name: Set /etc/logrotate.conf
  template:
    src: "logrotate.conf.j2"
    dest: "/etc/logrotate.conf"
    owner: "root"
    group: "root"
    mode: "0644"
  tags:
    - aspects_logrotate

- name: Set logrotate rules
  template:
    src: "logrotaterules.j2"
    dest: "/etc/logrotate.d/{{ item.0 }}"
    owner: "root"
    group: "root"
    mode: "0644"
  loop: "{{ aspects_logrotate_configs | dictsort }}"
  tags:
    - aspects_logrotate

- name: Check if /usr/lib/systemd/system/logrotate.timer exists
  when:
    - aspects_logrotate_manage_timer
  stat:
    path: /usr/lib/systemd/system/logrotate.timer
  register: inprocess_logrotate_timer
  tags:
    - aspects_logrotate

- name: Template /usr/lib/systemd/system/logrotate.timer
  when:
    - inprocess_logrotate_timer.stat is defined and inprocess_logrotate_timer.stat.exists
    - aspects_logrotate_manage_timer
  template:
    src: "logrotate.timer.j2"
    dest: "/usr/lib/systemd/system/logrotate.timer"
    owner: "root"
    group: "root"
    mode: "0644"
  notify: "reload logrotate.timer"
  tags:
    - aspects_logrotate

- name: Check if /etc/cron.daily/logrotate exists
  when:
    - aspects_logrotate_run_hourly_cron
  stat:
    path: /etc/cron.daily/logrotate
  register: inprocess_logrotate_cron_daily
  tags:
    - aspects_logrotate

- name: Copy /etc/cron.daily/logrotate to /etc/cron.hourly/logrotate
  when:
    - aspects_logrotate_run_hourly_cron
    - inprocess_logrotate_cron_daily.stat is defined and inprocess_logrotate_cron_daily.stat.exists
  copy:
    remote_src: "yes"
    src: "/etc/cron.daily/logrotate"
    dest: "/etc/cron.hourly/logrotate"
    owner: "root"
    group: "root"
    mode: "0755"
  tags:
    - aspects_logrotate

- name: Check if /etc/cron.hourly/logrotate exists
  when:
    - aspects_logrotate_run_hourly_cron
  stat:
    path: /etc/cron.hourly/logrotate
  register: inprocess_logrotate_cron_hourly
  tags:
    - aspects_logrotate

- name: Remove /etc/cron.daily/logrotate
  when:
    - aspects_logrotate_run_hourly_cron
    - inprocess_logrotate_cron_hourly.stat is defined and inprocess_logrotate_cron_hourly.stat.exists
  file:
    state: "absent"
    path: "/etc/cron.daily/logrotate"
  tags:
    - aspects_logrotate