---
- name: Set /etc/logrotate.conf
  template:
    src: "logrotate.conf.j2"
    dest: "/etc/logrotate.conf"
    owner: "root"
    group: "root"
    mode: "0644"
  tags:
    - aspects_logrotate

- name: Set logrotate rules
  template:
    src: "logrotaterules.j2"
    dest: "/etc/logrotate.d/{{ item.key }}"
    owner: "root"
    group: "root"
    mode: "0644"
  loop: "{{ aspects_logrotate_configs|dict2items }}"
  tags:
    - aspects_logrotate
