---
- name: Set /etc/logrotate.conf
  template:
    src: "logrotate.conf.j2"
    dest: "/etc/logrotate.conf"
    owner: "root"
    group: "root"
    mode: "0644"
  tags:
    - aspects_logrotate

- name: Set logrotate rules
  template:
    src: "logrotaterules.j2"
    dest: "/etc/logrotate.d/{{ item.0 }}"
    owner: "root"
    group: "root"
    mode: "0644"
  loop: "{{ aspects_logrotate_configs | dictsort }}"
  tags:
    - aspects_logrotate

- name: Check if /usr/lib/systemd/system/logrotate.timer exists
  when:
    - aspects_logrotate_manage_timer
  stat:
    path: /usr/lib/systemd/system/logrotate.timer
  register: inprocess_logrotate_timer
  tags:
    - aspects_logrotate

- name: Template /usr/lib/systemd/system/logrotate.timer
  when:
    - inprocess_logrotate_timer.stat.exists
    - aspects_logrotate_manage_timer
  template:
    src: "logrotate.timer.j2"
    dest: "/usr/lib/systemd/system/logrotate.timer"
    owner: "root"
    group: "root"
    mode: "0644"
  notify: "reload logrotate.timer"
  tags:
    - aspects_logrotate