---
- name: RedHat - Install logrotate packages with yum
  when:
    ansible_pkg_mgr == "yum" and
    item.value.state != 'default' and
    item.value.state != 'purged' and
    item.value.RedHat is defined
  yum:
    name: "{{ item.value.RedHat }}"
    state: "{{ item.value.state }}"
  with_dict: "{{ aspects_logrotate_packages }}"
  tags:
    - aspects_logrotate
    - aspects_logrotate_package_install
